---
name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write
  packages: write
  statuses: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add GHCR env var
        env:
          REPO: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "GHCR_REPO=ghcr.io/${REPO,,}" >>"${GITHUB_ENV}"
          echo "GHCR_TAG=${REF_NAME/\//_}" >>"${GITHUB_ENV}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:latest
            ${{ env.GHCR_REPO }}:${{ env.GHCR_TAG }}
          cache-from: type=gha,scope=${{ github.repository_id }}
          cache-to: type=gha,mode=max,scope=${{ github.repository_id }}
